server:
  port: 8000

spring:
  application:
    name: gateway-service

#eureka:
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://127.0.0.1:8761/eureka # eureka end point
