spring:
  config:
    activate:
      on-profile: deploy

  mvc:
    servlet:
      path: /api

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver # Database를 mariadb로 사용
    url: jdbc:mariadb://member-mariadb:3306/funco # mariadb 접속 정보
    username: funco-admin # mariadb 접속 시 입력할 username 정보
    password: funco302 # mariadb 접속 시 입력할 password 정보

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: false

  data:
    redis:
      host: main-redis
      port: 6379
      password: funco302

  jwt:
    token:
      secret-key: QTEwN2phbnNvcnJ5dGVhbWRuZmxya2RsZW1kZ2tmcmpkaWFrZmZsd2xha2RrcnBUc2kK
      refresh-secret-key: QTEwN2phbnNvcnJ5dGVhbWZsdm1mcHRubHhoem1zZHBlb2drZ2tzcmtxdGRsc2xSa3Jqc2VtZndsYWsK

  oauth:
    google:
      client-id: 298082348622-3gp2shappr5oth3a6ad9k2hvie46qck1.apps.googleusercontent.com
      client-secret-id: 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
      redirect-uri: https://funco.co.kr/redirect
      scope: profile,email

cloud:
  aws:
    credentials:
      accessKey: AKIA47CRVMDAYIPQNO5J
      secretKey: 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
    s3:
      bucket: fonco-image
    region:
      static: ap-northeast-2
    stack:
      auto: false

server:
  port: 8001

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: https://eureka.funco.co.kr/eureka/ # eureka end point by docker-network( 도커네트워크로 유레카 연결 )

  #  instance:
  #    prefer-ip-address: false  # IP 주소 대신 호스트명을 사용
  #    hostname: example.com     # HTTPS 도메인명
  #    non-secure-port-enabled: false # 비안전 포트 비활성화
  #    secure-port-enabled: true  # 안전 포트 활성화
  #    secure-port: 443  # HTTPS 표준 포트
  #
  #    status-page-url: https://${eureka.instance.hostname}/info
  #    health-check-url: https://${eureka.instance.hostname}/health
  #    home-page-url: https://${eureka.instance.hostname}/

  instance:
    hostname: member.funco.co.kr
    prefer-ip-address: false  # IP 주소 대신 호스트명을 사용
    secure-port-enabled: true
    secure-port: 443

