spring:
  config:
    activate:
      on-profile: deploy

  mvc:
    servlet:
      path: /api

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: k10a302.p.ssafy.io
      port: 6379
      password: funco302

  jwt:
    token:
      secret-key: QTEwN2phbnNvcnJ5dGVhbWRuZmxya2RsZW1kZ2tmcmpkaWFrZmZsd2xha2RrcnBUc2kK
      refresh-secret-key: QTEwN2phbnNvcnJ5dGVhbWZsdm1mcHRubHhoem1zZHBlb2drZ2tzcmtxdGRsc2xSa3Jqc2VtZndsYWsK

  oauth:
    google:
      client-id: 298082348622-3gp2shappr5oth3a6ad9k2hvie46qck1.apps.googleusercontent.com
      client-secret-id: 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
      redirect-uri: https://funco.co.kr/redirect
      scope: profile,email

  cloud:
    openfeign:
      okhttp:
        enabled: true # patch를 쓰기 위해 feign okhttp 설정

server:
  port: 8001

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: https://eureka.funco.co.kr/eureka/ # eureka end point by docker-network( 도커네트워크로 유레카 연결 )

  instance:
    hostname: auth.funco.co.kr
    prefer-ip-address: false  # IP 주소 대신 호스트명을 사용
    secure-port-enabled: true
    secure-port: 443

# feign client 상세 로그 출력 하도록 설정
logging:
  level:
    com.found_404.funco.trade.client: DEBUG

